name: InventoryBomb
version: ${project.version}
main: net.dohaw.play.inventorybomb.InventoryBombPlugin
api-version: 1.13
depend:
  - CoreAPI
commands:
  inventorybomb:
    aliases:
      - ib
      - inventoryb
      - invb
      - invbomb

permissions:
  inventorybomb.use:
    default: op
